var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "attrs.h", "attrs_8h_source.html", null ],
    [ "debug.h", "debug_8h_source.html", null ],
    [ "idt.h", "idt_8h_source.html", null ],
    [ "io.h", "io_8h_source.html", null ],
    [ "kernel.h", "kernel_8h_source.html", null ],
    [ "kmalloc.h", "kmalloc_8h_source.html", null ],
    [ "ksystem.h", "ksystem_8h_source.html", null ],
    [ "lib.h", "lib_8h_source.html", null ],
    [ "list.h", "list_8h_source.html", null ],
    [ "malloc.h", "malloc_8h_source.html", null ],
    [ "mmap.h", "mmap_8h_source.html", null ],
    [ "paging.h", "paging_8h_source.html", null ],
    [ "pfa.h", "pfa_8h_source.html", null ],
    [ "pfh_fifo.h", "pfh__fifo_8h_source.html", null ],
    [ "pfh_random.h", "pfh__random_8h_source.html", null ],
    [ "pfh_second.h", "pfh__second_8h_source.html", null ],
    [ "pic.h", "pic_8h_source.html", null ],
    [ "pqueue.h", "pqueue_8h_source.html", null ],
    [ "pra.h", "pra_8h_source.html", null ],
    [ "pra_err.h", "pra__err_8h_source.html", null ],
    [ "pra_unit.h", "pra__unit_8h_source.html", null ],
    [ "random.h", "random_8h_source.html", null ],
    [ "serial.h", "serial_8h_source.html", null ],
    [ "string_utils.h", "string__utils_8h_source.html", null ],
    [ "suite_runner.h", "suite__runner_8h.html", "suite__runner_8h" ],
    [ "terminal.h", "terminal_8h_source.html", null ],
    [ "timer.h", "timer_8h_source.html", null ]
];